---
version: 2

jobs:
  shellcheck:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: 'Install ShellCheck'
          command: |
            apt-get -y update && apt-get -y install shellcheck
      - run:
          name: 'Run ShellCheck'
          command: |
            shellcheck hashicorp-install.sh
  test-alpine:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: 'Install Prerequisites'
          command: |
            apk add gnupg unzip
      - run:
          name: 'Run Tests on Alpine'
          command: &test_install_command |
            # Install all packages.
            for package in consul packer terraform; do
              ./hashicorp-install.sh $package
            done

            # Test installing Packer at a specific version and path.
            PACKAGE_VERSION=1.4.5 PACKAGE_PATH=/usr/bin ./hashicorp-install.sh packer
            if [ "$(/usr/bin/packer --version)" != "1.4.5" ]; then
              echo "Couldn't install Packer at a specific version."
              exit 1
            fi
  test-centos:
    docker:
      - image: centos
    steps:
      - checkout
      - run:
          name: 'Install Prerequisites'
          command: |
            yum -y install unzip
      - run:
          name: 'Run Tests on CentOS'
          command: *test_install_command
  test-ubuntu:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: 'Install Prerequisites'
          command: |
            apt-get -y update && apt-get -y install wget unzip
      - run:
          name: 'Run Tests on Ubuntu'
          command: *test_install_command

workflows:
  version: 2
  tests:
    jobs:
      - shellcheck
      - test-alpine:
          requires:
            - shellcheck
      - test-centos:
          requires:
            - shellcheck
      - test-ubuntu:
          requires:
            - shellcheck
