---
version: 2

jobs:
  shellcheck:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: 'install shellcheck'
          command: |
            apt-get -y update && apt-get -y install shellcheck
      - run:
          name: 'run shellcheck'
          command: |
            shellcheck hashicorp-install.sh

workflows:
  version: 2
  tests:
    jobs:
      - shellcheck
